export const SET_DEFAULT_LOCATION = "SET_DEFAULT_LOCATION";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_PENDING = "FETCH_LOCATION_PENDING";
export const FETCH_LOCATION_FULFILLED = "FETCH_LOCATION_FULFILLED";
export const FETCH_LOCATION_REJECTED = "FETCH_LOCATION_REJECTED";
