export const SET_DEFAULT_LOCATION = "SET_DEFAULT_LOCATION";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_PENDING = "FETCH_LOCATION_PENDING";
export const FETCH_LOCATION_FULFILLED = "FETCH_LOCATION_FULFILLED";
export const FETCH_LOCATION_REJECTED = "FETCH_LOCATION_REJECTED";

export const FETCH_STOPS = "FETCH_STOPS";
export const FETCH_STOPS_PENDING = "FETCH_STOPS_PENDING";
export const FETCH_STOPS_FULFILLED = "FETCH_STOPS_FULFILLED";
export const FETCH_STOPS_REJECTED = "FETCH_STOPS_REJECTED";

export const FETCH_BUS_TIMES = "FETCH_BUS_TIMES";
export const FETCH_BUS_TIMES_PENDING = "FETCH_BUS_TIMES_PENDING";
export const FETCH_BUS_TIMES_FULFILLED = "FETCH_BUS_TIMES_FULFILLED";
export const FETCH_BUS_TIMES_REJECTED = "FETCH_BUS_TIMES_REJECTED";

export const TOGGLE_CARD_SIZE = "TOGGLE_CARD_SIZE";
export const EXPAND_CARD_SIZE = "EXPAND_CARD_SIZE";
export const COLLAPSE_CARD_SIZE = "COLLAPSE_CARD_SIZE";
